services:
  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    container_name: server
    ports:
      - "3333:3333"
    depends_on:
      postgres:
        condition: service_healthy

  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    container_name: client
    ports:
      - "3000:3000"

volumes:
  postgres_database:
