api:
    dashboard: true
    insecure: false
    debug: false
entryPoints:
    web:
        address: ":80"
        http:
            redirections:
                entryPoint:
                    to: websecure
                    scheme: https
    websecure:
        address: ":443"
serversTransport:
    insecureSkipVerify: true
providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false
certificatesResolvers:
    letencrypt:
        acme:
            email: nathanfouere@tutanota.com
            storage: /certs/acme.json
            # caServer: https://acme-v02.api.letsencrypt.org/directory a remettre
            caServer: https://acme-staging-v02.api.letsencrypt.org/directory
            httpChallenge:
                entryPoint: web