apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: president-challenge
  namespace: president-challenge
spec:
  interval: 5m
  url: https://github.com/NathanFouere/president-challenge
