apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: president-challenge
  namespace: president-challenge
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    ingress:
      hosts:
        - host: president-challenge.production
          paths:
            - path: /
              pathType: ImplementationSpecific
