import { BaseSchema } from '@adonisjs/lucid/schema';
import { EventType } from '@shared/dist/event/event-type.js';

export default class extends BaseSchema {
  public async up() {
    this.schema.raw(`
      ALTER TABLE event_definitions
      DROP CONSTRAINT event_definitions_type_check;

      ALTER TABLE event_definitions
      ADD CONSTRAINT event_definitions_type_check
      CHECK (type IN (
        '${EventType.Choice}',
        '${EventType.SuperEvent}',
        '${EventType.Historical}',
        '${EventType.Autogenerated}'
        ));
    `);
  }

  public async down() {
    this.schema.raw(`
      ALTER TABLE event_definitions
      DROP CONSTRAINT event_definitions_type_check;

      ALTER TABLE event_definitions
      ADD CONSTRAINT event_definitions_type_check
        CHECK (type IN (
                         '${EventType.Choice}',
                         '${EventType.SuperEvent}',
                         '${EventType.Historical}'
          ));
    `);
  }
}
