import { BaseSchema } from '@adonisjs/lucid/schema';

export default class extends BaseSchema {
  async up() {
    this.schema.alterTable('event_definitions', (table) => {
      table.boolean('autogenerated').notNullable().defaultTo(false);
    });
  }

  async down() {
    this.schema.alterTable('event_definitions', (table) => {
      table.dropColumn('autogenerated');
    });
  }
}
