import { inject } from '@adonisjs/core';

// eslint-disable-next-line @typescript-eslint/consistent-type-imports
import IChoiceRepository from '#event/domain/repository/i_choice_repository';
// eslint-disable-next-line @typescript-eslint/consistent-type-imports
import IEventRepository from '#event/domain/repository/i_event_repository';
import type { StartupProcessorStep } from '#common/startup/startup_processor_step';
import { anEvent } from '#event/application/builders/event_builder';
import { aChoice } from '#event/application/builders/choice_builder';
// eslint-disable-next-line @typescript-eslint/consistent-type-imports
import IGetEventDefinitionsByGameDefinitionQueryHandler
  from '#event/application/queries/i_get_event_definitions_by_game_definition_query_handler';
import GetEventDefinitionsByGameDefinitionQuery
  from '#event/application/queries/get_event_definitions_by_game_definition_query';
// eslint-disable-next-line @typescript-eslint/consistent-type-imports
import IGetChoiceDefinitionsByGameDefinitionQueryHandler
  from '#event/application/queries/i_get_choice_definitions_by_game_definition_query_handler';
import GetChoiceDefinitionsByGameDefinitionQuery
  from '#event/application/queries/get_choice_definitions_by_game_definition_query';

@inject()
export class EventStartupService implements StartupProcessorStep {
  constructor(
    private readonly choiceRepository: IChoiceRepository,
    private readonly eventRepository: IEventRepository,
    private readonly getEventDefinitionsByGameDefinitionQueryHandler: IGetEventDefinitionsByGameDefinitionQueryHandler,
    private readonly getChoiceDefinitionsByGameDefinitionQueryHandler: IGetChoiceDefinitionsByGameDefinitionQueryHandler,
  ) {
  }

  public async execute(gameId: number, gameDefinitionIdentifier: string): Promise<void> {
    const eventDefinitions = await this.getEventDefinitionsByGameDefinitionQueryHandler.handle(
      new GetEventDefinitionsByGameDefinitionQuery(gameDefinitionIdentifier),
    );
    const choiceDefinitions = await this.getChoiceDefinitionsByGameDefinitionQueryHandler.handle(
      new GetChoiceDefinitionsByGameDefinitionQuery(gameDefinitionIdentifier),
    );

    const events = [];
    for (const eventDefinition of eventDefinitions) {
      if (eventDefinition.autogenerated) {
        continue;
      }
      events.push(anEvent()
        .withGameId(gameId)
        .withTurn(eventDefinition.turn)
        .withDisplayable(eventDefinition.isDisplayableByDefault)
        .withBeenRead(false)
        .withIsAvailable(eventDefinition.isAvailableByDefault)
        .withDefinitionId(eventDefinition.id)
        .build(),
      );
    }
    await this.eventRepository.createMany(events);

    // TODO => could be improved
    const choices = [];
    for (const choiceDefinition of choiceDefinitions) {
      const choiceEventId = events.find(event => event.definitionId === choiceDefinition.eventDefinitionId)!.id;
      const choiceTriggerEventId = events.find(event => event.definitionId === choiceDefinition.triggerEventDefinitionId)?.id;

      choices.push(aChoice()
        .withEventId(choiceEventId)
        .withTriggerEventId(choiceTriggerEventId)
        .withDefinitionId(choiceDefinition.id)
        .withGameId(gameId)
        .build(),
      );
    }

    await this.choiceRepository.createMany(choices);
  }
}
