apiVersion: v1
kind: Service
metadata:
  name: president-challenge-client
  labels:
    app.kubernetes.io/name: president-challenge
    app.kubernetes.io/component: client
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: president-challenge
    app.kubernetes.io/component: client