apiVersion: apps/v1
kind: Deployment
metadata:
  name: president-challenge-minio
  labels:
    app.kubernetes.io/name: president-challenge
    app.kubernetes.io/component: minio
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: president-challenge
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: president-challenge
        app.kubernetes.io/component: minio
    spec:
      containers:
        - name: minio
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          ports:
            - name: api
              containerPort: {{ .Values.minio.service.apiPort }}
              protocol: TCP
            - name: console
              containerPort: {{ .Values.minio.service.consolePort }}
              protocol: TCP
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: {{ .Values.secrets.keys.minioRootUser }}
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: {{ .Values.secrets.keys.minioRootPassword }}
            - name: MINIO_DEFAULT_BUCKETS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: {{ .Values.secrets.keys.minioDefaultBuckets }}
            - name: MINIO_CONSOLE_ADDRESS
              value: {{ .Values.minio.config.consoleAddress | quote }}
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: president-challenge-minio