apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: president-challenge-minio
  labels:
    app.kubernetes.io/name: president-challenge
    app.kubernetes.io/component: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.storage.size }}
  {{- if .Values.minio.storage.storageClassName }}
  storageClassName: {{ .Values.minio.storage.storageClassName }}
  {{- end }}