apiVersion: v1
kind: Service
metadata:
  name: president-challenge-minio
  labels:
    app.kubernetes.io/name: president-challenge
    app.kubernetes.io/component: minio
spec:
  type: {{ .Values.minio.service.type }}
  ports:
    - name: api
      port: {{ .Values.minio.service.apiPort }}
      targetPort: {{ .Values.minio.service.apiPort }}
      protocol: TCP
    - name: console
      port: {{ .Values.minio.service.consolePort }}
      targetPort: {{ .Values.minio.service.consolePort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: president-challenge
    app.kubernetes.io/component: minio