apiVersion: v1
kind: Service
metadata:
  name: president-challenge-postgres
  labels:
    app.kubernetes.io/name: president-challenge
    app.kubernetes.io/component: postgres
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.targetPort }}
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: president-challenge
    app.kubernetes.io/component: postgres