apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: president-challenge-postgres
  labels:
    app.kubernetes.io/name: president-challenge
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
  {{- if .Values.postgres.storage.storageClassName }}
  storageClassName: {{ .Values.postgres.storage.storageClassName }}
  {{- end }}