apiVersion: v1
kind: Service
metadata:
  name: president-challenge-rustfs
  labels:
    app.kubernetes.io/name: president-challenge
    app.kubernetes.io/component: rustfs
spec:
  type: {{ .Values.rustfs.service.type }}
  ports:
    - name: api
      port: {{ .Values.rustfs.service.apiPort }}
      targetPort: {{ .Values.rustfs.service.apiPort }}
      protocol: TCP
    - name: console
      port: {{ .Values.rustfs.service.consolePort }}
      targetPort: {{ .Values.rustfs.service.consolePort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: president-challenge
    app.kubernetes.io/component: rustfs