apiVersion: v1
kind: Service
metadata:
  name: president-challenge-server
  labels:
    app.kubernetes.io/name: president-challenge
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: president-challenge
    app.kubernetes.io/component: server