apiVersion: apps/v1
kind: Deployment
metadata:
  name: president-challenge-server
  labels:
    app.kubernetes.io/name: president-challenge
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: president-challenge
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: president-challenge
        app.kubernetes.io/component: server
    spec:
      containers:
        - name: president-challenge-server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.server.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: president-challenge-server-config
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: {{ .Values.secrets.keys.appKey }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: {{ .Values.secrets.keys.postgresPassword }}

            - name: RUSTFS_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: {{ .Values.secrets.keys.rustfsRootUser }}
            - name: RUSTFS_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: {{ .Values.secrets.keys.rustfsRootPassword }}
            - name: RUSTFS_DEFAULT_BUCKETS
              value: {{ .Values.rustfs.config.defaultBuckets | quote }}
            - name: RUSTFS_ENDPOINT
              value: "http://president-challenge-rustfs:{{ .Values.rustfs.service.apiPort }}"
            - name: RUSTFS_REGION
              value: {{ .Values.rustfs.config.region | quote }}
