name: President Challenge Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build packages
        run: pnpm run build
        env:
          NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}

      - name: Type Check
        run: pnpm run typecheck

      - name: Lint Check
        run: pnpm run lint:check

      - name: Run tests and coverage
        run: pnpm run coverage
        env:
          ADMINJS_RELATIONS_LICENSE: ${{ secrets.ADMINJS_RELATIONS_LICENSE }}

  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && github.ref_name == 'main'
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker (Server)
        id: meta-server
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/president-challenge-server

      - name: Build and push Docker image (Server)
        id: push-server
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          target: server
          push: true
          tags: ${{ steps.meta-server.outputs.tags }}
          labels: ${{ steps.meta-server.outputs.labels }}
          build-args: |
            NUXT_UI_PRO_LICENSE=${{ secrets.NUXT_UI_PRO_LICENSE }}

      - name: Extract metadata (tags, labels) for Docker (Client)
        id: meta-client
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/president-challenge-client

      - name: Build and push Docker image (Client)
        id: push-client
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          target: client
          push: true
          tags: ${{ steps.meta-client.outputs.tags }}
          labels: ${{ steps.meta-client.outputs.labels }}
          build-args: |
            NUXT_UI_PRO_LICENSE=${{ secrets.NUXT_UI_PRO_LICENSE }}

      - name: Generate artifact attestation (Server)
        uses: actions/attest@v4
        with:
          subject-name: index.docker.io/${{ secrets.DOCKER_USERNAME }}/president-challenge-server
          subject-digest: ${{ steps.push-server.outputs.digest }}
          push-to-registry: true

      - name: Generate artifact attestation (Client)
        uses: actions/attest@v4
        with:
          subject-name: index.docker.io/${{ secrets.DOCKER_USERNAME }}/president-challenge-client
          subject-digest: ${{ steps.push-client.outputs.digest }}
          push-to-registry: true

  helm:
    name: Build and Push Helm Chart
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && github.ref_name == 'main'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.TOKEN }}"
